pub const ACTIONS: [&str; 6] = [
    "create",
    "issue",
    "retire",
    "transfer",
    "open",
    "close",
];

pub const ACCOUNTS: [&str; 52] = [
    "eosnationftw",
    "eosnationinc",
    "eosnationamb",
    "eosnationdon",
    "sidecontract",
    "ypjitialbhfs",
    ".gems",
    "gems ",
    "gem",
    "chllnge.gems",
    "hongbao.gems",
    "unpack.gems",
    "dot.gems",
    "gbk.gems ",
    "acone.gems ",
    "distro.gems ",
    "d.blend.gems ",
    "gavinski.gems ",
    "eosnfteosnft ",
    "thangka.gem ",
    "pomelo",
    "blend.pomelo",
    "mine.pomelo",
    "promo.pomelo",
    "cpu.pomelo",
    "d.clm.pomelo",
    "stats.pomelo",
    "app.pomelo",
    "play.pomelo",
    "pfp.pomelo",
    "match.pomelo",
    "fee.pomelo",
    "tree.pomelo",
    "sx",
    "cpu.sx",
    "push.sx",
    "fee.sx",
    "eusd.sx",
    "bank.sx",
    "stable.sx",
    "swap.sx",
    "lucky.sx",
    "basic.sx",
    "hft.sx",
    "gateway.sx",
    "registry.sx",
    "whitelist.sx",
    "nft.sx",
    "rental.sx",
    "ops.sx",
    "box.sx",
    "timelock.sx",
];
