{
 "title": "Mechanics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Drift Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "head_block_drift", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Block Number",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(last_block_number)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Block Time",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(last_block_timestamp * 1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Schedule Version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "max(schedule_version)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Producer Usage",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg by(producer) (producer_usage)",
     "legendFormat": "{{producer}}"
    }
   ]
  },
  {
   "title": "Producer Usage Histogram",
   "type": "histogram",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(histogram_producer_usage_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Head Block Drift",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "avg(head_block_drift)", "legendFormat": "__auto" }
   ]
  }
 ]
}